services:
  python:
    container_name: elastic2csv
    build: .
    volumes:
      - ./run:/usr/src/run
      - ./elastic2csv:/usr/src/elastic2csv
    env_file:
      - .env
    working_dir: /usr/src/elastic2csv
    command: sh ../run/new.sh
